sudo: false

language: php

cache:
  directories:
    - "$HOME/.composer/cache"
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - openssl aes-256-cbc -K $encrypted_f21abcc37842_key -iv $encrypted_f21abcc37842_iv
    -in secrets.tar.enc -out secrets.tar -d
  - travis_retry composer self-update

install:
  - travis_retry composer install --optimize-autoloader --prefer-dist --no-interaction
  - composer info -i

script:
  - here call phpunit

after_script:
  - something more

after_success: 
