sudo: false

language: php

cache:
  directories:
    - "$HOME/.composer/cache"
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_DEPLOYMENT=true
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini ; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction
  - composer info -i

script:
  - vendor/bin/phpunit

after_success:
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_PULL_REQUEST == 'false' ]]; then composer install --no-dev --prefer-dist --no-interaction ; fi
  - if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./bin/deploy.sh ; fi